### ISSUE TITLE
Overlay does not show unless window is resized (Mac)

### ISSUE THREAD

**Issue by Antrikshy** [anseki/jquery-plainoverlay#5]
After adding an overlay to an element, I have to resize the window ever so slightly to make the overlay actually show up. This happens on Safari, Chrome and Firefox (Mac), all current versions.

Known? Workarounds?

**Comment by Antrikshy** [comment]
Actually it may be because of the way this particular element is dynamically changed elsewhere. Never mind.

**Comment by anseki** [comment]
Hi Antrikshy, thanx for your post.
If you find problem, let me know. :smiley:

**Comment by Antrikshy** [comment]
The problem was that the overlay was too tiny. I was creating it when the dimensions of the loading element were not finalized yet.

**Comment by anseki** [comment]
I see.
Thank you for your report.
