### ISSUE TITLE
Show on top with kendo UI 

### ISSUE THREAD

**Issue by bzamfir** [anseki/jquery-plainoverlay#6]
Hi,

I'm using your lib in my app, and it is working fine.
However, I have an issue with it.

My app uses Kendo UI, and kendoui elements are rendered on top of the overlay (see attachment)

How can I make it to show on top?

Thank you

![2015-11-14_2025](https://cloud.githubusercontent.com/assets/4658652/11165110/2434fb58-8b0e-11e5-9371-6d42bf956c0a.png)

**Comment by anseki** [comment]
Hi bzamfir, thank you for your post.

I don't know which element you set the overlay to, but it seems that the [`zIndex`](https://github.com/anseki/jquery-plainoverlay#zindex) option of overlay is smaller than that of other elements.
Try to set a larger value to `zIndex` option.

**Comment by bzamfir** [comment]
Thanks for quick reply
You pointed me in the right direction.

I used a generic function I call to set the overlay on an container element
on the area I'm updating with ajax, as below (my function is using  j$ for
jquery because the app uses also mootools which takes over $ var):

function showProgressJ(on, target, message) {
    if (target.substr(0, 1) !== '#') target = '#' + target;

    var $target = j$(target);
    if ($target)
        $target.show();

    if (!on)
        j$(target).plainOverlay('hide');
    else
        j$(target).plainOverlay('show',
            {zIndex: 90000 }
        );
}

On the page I use

    showProgressJ(true, 'dvProgress', 'Saving ...');

   ....

    <div id="dvProgress" class="progress-overlay"></div>

But that worked as I show in the screen capture.
I was trying to apply the zindex to planOverlay itself.

But after your reply I applied the zindex to dvProgress div, and this made
it work ok.

But I have another question

Is is possible to display a dynamic text on progress overlay, as below  *Please
wait ...*  ?
As you see above, my function has a message *parameter* (for compatibility
with previous version based on mootools), but I didn't find an option to
write a test on the progress overlay.

[image: Imagini inline 1]

Thank you







2015-11-14 21:21 GMT+02:00 anseki <notifications@github.com>:

**Comment by anseki** [comment]
plainOverlay covers a specified element (not outside elements of specified element). Therefore your modification may be right.
But your screen capture seems that another element for only overlay covers other elements (form elements, etc.). If you want to make overlay cover all of the page, specify `<body>` element to plainOverlay. You don't have to make another element for only overlay. For example, http://anseki.github.io/jquery-plainoverlay/

So, of course you can specify your element (your message or anything) to display it on the overlay.
See `progress` option and DEMO:
http://anseki.github.io/jquery-plainoverlay/#progress

**Comment by bzamfir** [comment]
Thank you

Bogdan

2015-11-14 22:41 GMT+02:00 anseki <notifications@github.com>:

**Comment by anseki** [comment]
:smiley:
So, the issue was solved? and this issue is closed?

**Comment by bzamfir** [comment]
Yes. And thank you for your time and help
Pe 15 nov. 2015 09:51, "anseki" <notifications@github.com> a scris:

**Comment by anseki** [comment]
I close this issue that is still opened.
Please reopen it if not solved.
