### ISSUE TITLE
no option to check if plainOverlay is showing

### ISSUE THREAD

**Issue by genius257** [anseki/jquery-plainoverlay#9]
It would be nice to have an option to see if plainOverlay is showing, without using events.

**Comment by anseki** [comment]
`isShown` property of internal object may help you:
```js
$element.data('plainOverlay').isShown // `true` if it's showing, otherwise `false`
```

**Comment by genius257** [comment]
perfect! many thanks

**Comment by anseki** [comment]
😃 
So, this issue was solved? It's not yet closed.

**Comment by genius257** [comment]
Yes  :smile:
